### PR TITLE
Update to newer yodeploy

### PR DESCRIPTION
**Pull request by fr33l**
https://github.com/yola/production/issues/3817

### CODE REVIEW

**Comment by stefanor** [comment]
I bet the virtualenv hacks in here are going to break, with the new pip based virtualenvs. We're going to have to test this on an int-env.

**Comment by RayeN** [comment]
Didn't we want to kill this repo?

**Comment by fr33l** [comment]
actually, this PR led to conversation about killing graphite, so I think yea, this can be closed.

**Comment by stefanor** [comment]
Opened a ticket to actually kill it: yola/production#4213

**Pull request closed without merging**
